
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../ext/src",
  "Packt": "../../app",
  "Ext.rtl.EventObjectImpl": "../../ext/src/rtl/EventObject.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Packt.store.film.FilmActors": [],
  "Packt.controller.mail.Mail": [],
  "Packt.view.sakila.SakilaGrid": [],
  "Packt.model.customer.Customer": [],
  "Packt.model.menu.Root": [],
  "Packt.model.film.FilmInventory": [],
  "Packt.controller.staticData.AbstractController": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Packt.store.film.Films": [],
  "Packt.controller.security.Users": [],
  "Packt.store.Menu": [],
  "Packt.view.security.GroupsList": [],
  "Packt.controller.cms.Films": [],
  "Packt.model.staticData.City": [],
  "Packt.controller.Login": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Packt.view.customer.Customers": [],
  "Ext.ux.DataView.DragSelector": [],
  "Packt.store.film.SearchActors": [],
  "Packt.store.staticData.Languages": [],
  "Packt.model.film.Film": [],
  "Packt.view.Translation": [],
  "Packt.store.staticData.Cities": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Packt.view.reports.SalesFilmCategoryColumn": [],
  "Packt.view.toolbar.CancelSave": [],
  "Packt.view.Login": [],
  "Packt.model.mail.MailMessage": [],
  "Packt.view.security.GroupPermissions": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Packt.view.staticData.Countries": [],
  "Packt.model.security.Group": [],
  "Ext.ux.PreviewPlugin": [],
  "Packt.store.mail.MailMessages": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "Packt.view.staticData.Categories": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Packt.view.Header": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Packt.view.film.SearchCategory": [],
  "Packt.view.Main": [],
  "Ext.ux.event.Recorder": [],
  "Packt.util.MD5": [],
  "Packt.controller.reports.SalesFilmCategory": [],
  "Packt.model.film.SearchActor": [],
  "Packt.view.sakila.SearchWindow": [],
  "Packt.controller.Menu": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Packt.util.Util": [],
  "Packt.view.toolbar.SearchAddDelete": [],
  "Packt.view.mail.MailList": [],
  "Ext.ux.TabScrollerMenu": [],
  "Packt.view.mail.MailPreview": [],
  "Packt.view.staticData.Cities": [],
  "Ext.ux.IFrame": [],
  "Packt.store.staticData.Actors": [],
  "Packt.store.staticData.Countries": [],
  "Packt.view.reports.SalesFilmCategoryBar": [],
  "Ext.ux.form.SearchField": [],
  "Packt.view.film.FilmCategories": [],
  "Packt.store.film.FilmCategories": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Packt.store.reports.SalesFilmCategory": [],
  "Packt.view.MyViewport": [],
  "Ext.ux.TreePicker": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Ext.ux.BoxReorderer": [],
  "Packt.store.customer.Customers": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "Packt.store.security.Permissions": [],
  "Packt.view.staticData.Languages": [],
  "Ext.ux.FieldReplicator": [],
  "Packt.view.menu.Accordion": [],
  "Packt.view.security.UsersList": [],
  "Packt.view.staticData.Actors": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Packt.model.sakila.Sakila": [],
  "Packt.view.film.FilmWindow": [],
  "Packt.view.security.Profile": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Packt.view.sakila.WindowForm": [],
  "Packt.store.security.Users": [],
  "Ext.ux.GMapPanel": [],
  "Packt.store.mail.MailMenu": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Packt.util.Alert": [],
  "Packt.store.film.Ratings": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [],
  "Packt.view.toolbar.AddEditDelete": [],
  "Ext.ux.DataView.Animated": [],
  "Packt.view.security.Groups": [],
  "Packt.view.reports.SalesFilmCategory": [],
  "Packt.model.film.FilmCategory": [],
  "Packt.store.staticData.Abstract": [],
  "Packt.model.staticData.Category": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Packt.model.staticData.Country": [],
  "Packt.util.SessionMonitor": [],
  "Packt.view.mail.NewMail": [],
  "Packt.store.staticData.Categories": [],
  "Packt.view.Viewport": [],
  "Packt.view.film.SearchActor": [],
  "Packt.view.MainPanel": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Packt.view.film.FilmActors": [],
  "Ext.ux.RowExpander": [],
  "Packt.controller.security.Groups": [],
  "Ext.ux.event.Player": [],
  "Packt.store.security.Groups": [],
  "Packt.model.staticData.Language": [],
  "Packt.model.menu.Item": [],
  "Packt.store.film.FilmInventories": [],
  "Packt.view.menu.Item": [],
  "Ext.ux.ToolbarDroppable": [],
  "Packt.view.toolbar.CancelClearAdd": [],
  "Packt.view.authentication.CapsLockTooltip": [],
  "Packt.controller.Abstract": [],
  "Packt.model.security.User": [],
  "Packt.view.security.Users": [],
  "Ext.ux.event.Maker": [],
  "Packt.controller.Main": [],
  "Packt.model.customer.Address": [],
  "Packt.view.security.GroupsEdit": [],
  "Packt.view.reports.SalesFilmCategoryPie": [],
  "Ext.ux.DataView.Draggable": [],
  "Packt.controller.TranslationManager": [],
  "Ext.ux.TabCloseMenu": [],
  "Packt.view.mail.MailMenu": [],
  "Packt.view.staticData.AbstractGrid": [],
  "Packt.proxy.StaticData": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Packt.model.staticData.Actor": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Packt.view.film.Films": [],
  "Packt.proxy.Sakila": [],
  "Packt.store.customer.Addresses": [],
  "Packt.view.mail.MailContainer": []
});
Ext.ClassManager.addNameAliasMappings({
  "Packt.store.film.FilmActors": [],
  "Packt.controller.mail.Mail": [],
  "Packt.view.sakila.SakilaGrid": [
    "widget.sakilagrid"
  ],
  "Packt.model.customer.Customer": [],
  "Packt.model.menu.Root": [],
  "Packt.model.film.FilmInventory": [],
  "Packt.controller.staticData.AbstractController": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Packt.store.film.Films": [],
  "Packt.controller.security.Users": [],
  "Packt.store.Menu": [],
  "Packt.view.security.GroupsList": [
    "widget.groupslist"
  ],
  "Packt.controller.cms.Films": [],
  "Packt.model.staticData.City": [],
  "Packt.controller.Login": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Packt.view.customer.Customers": [
    "widget.customersgrid"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "Packt.store.film.SearchActors": [],
  "Packt.store.staticData.Languages": [],
  "Packt.model.film.Film": [],
  "Packt.view.Translation": [
    "widget.translation"
  ],
  "Packt.store.staticData.Cities": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Packt.view.reports.SalesFilmCategoryColumn": [
    "widget.salesfilmcategorycol"
  ],
  "Packt.view.toolbar.CancelSave": [
    "widget.cancelsave"
  ],
  "Packt.view.Login": [
    "widget.login"
  ],
  "Packt.model.mail.MailMessage": [],
  "Packt.view.security.GroupPermissions": [
    "widget.grouppermissions"
  ],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Packt.view.staticData.Countries": [
    "widget.countriesgrid"
  ],
  "Packt.model.security.Group": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Packt.store.mail.MailMessages": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Packt.view.staticData.Categories": [
    "widget.categoriesgrid"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Packt.view.Header": [
    "widget.appheader"
  ],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Packt.view.film.SearchCategory": [
    "widget.searchcategory"
  ],
  "Packt.view.Main": [],
  "Ext.ux.event.Recorder": [],
  "Packt.util.MD5": [],
  "Packt.controller.reports.SalesFilmCategory": [],
  "Packt.model.film.SearchActor": [],
  "Packt.view.sakila.SearchWindow": [
    "widget.searchWindow"
  ],
  "Packt.controller.Menu": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Packt.util.Util": [],
  "Packt.view.toolbar.SearchAddDelete": [
    "widget.searchadddelete"
  ],
  "Packt.view.mail.MailList": [
    "widget.maillist"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Packt.view.mail.MailPreview": [
    "widget.mailpreview"
  ],
  "Packt.view.staticData.Cities": [
    "widget.citiesgrid"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Packt.store.staticData.Actors": [],
  "Packt.store.staticData.Countries": [],
  "Packt.view.reports.SalesFilmCategoryBar": [
    "widget.salesfilmcategorybar"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Packt.view.film.FilmCategories": [
    "widget.filmcategories"
  ],
  "Packt.store.film.FilmCategories": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Packt.store.reports.SalesFilmCategory": [],
  "Packt.view.MyViewport": [
    "widget.mainviewport"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Ext.ux.BoxReorderer": [],
  "Packt.store.customer.Customers": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Packt.store.security.Permissions": [],
  "Packt.view.staticData.Languages": [
    "widget.languagesgrid"
  ],
  "Ext.ux.FieldReplicator": [],
  "Packt.view.menu.Accordion": [
    "widget.mainmenu"
  ],
  "Packt.view.security.UsersList": [
    "widget.userslist"
  ],
  "Packt.view.staticData.Actors": [
    "widget.actorsgrid"
  ],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Packt.model.sakila.Sakila": [],
  "Packt.view.film.FilmWindow": [
    "widget.filmwindow"
  ],
  "Packt.view.security.Profile": [
    "widget.profile"
  ],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Packt.view.sakila.WindowForm": [
    "widget.windowform"
  ],
  "Packt.store.security.Users": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Packt.store.mail.MailMenu": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Packt.util.Alert": [],
  "Packt.store.film.Ratings": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Packt.view.toolbar.AddEditDelete": [
    "widget.addeditdelete"
  ],
  "Ext.ux.DataView.Animated": [],
  "Packt.view.security.Groups": [
    "widget.groups"
  ],
  "Packt.view.reports.SalesFilmCategory": [
    "widget.salesfilmcategory"
  ],
  "Packt.model.film.FilmCategory": [],
  "Packt.store.staticData.Abstract": [],
  "Packt.model.staticData.Category": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Packt.model.staticData.Country": [],
  "Packt.util.SessionMonitor": [],
  "Packt.view.mail.NewMail": [
    "widget.newmail"
  ],
  "Packt.store.staticData.Categories": [],
  "Packt.view.Viewport": [],
  "Packt.view.film.SearchActor": [
    "widget.searchactor"
  ],
  "Packt.view.MainPanel": [
    "widget.mainpanel"
  ],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Packt.view.film.FilmActors": [
    "widget.filmactors"
  ],
  "Ext.ux.RowExpander": [],
  "Packt.controller.security.Groups": [],
  "Ext.ux.event.Player": [],
  "Packt.store.security.Groups": [],
  "Packt.model.staticData.Language": [],
  "Packt.model.menu.Item": [],
  "Packt.store.film.FilmInventories": [],
  "Packt.view.menu.Item": [
    "widget.mainmenuitem"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "Packt.view.toolbar.CancelClearAdd": [
    "widget.cancelclearadd"
  ],
  "Packt.view.authentication.CapsLockTooltip": [
    "widget.capslocktooltip"
  ],
  "Packt.controller.Abstract": [],
  "Packt.model.security.User": [],
  "Packt.view.security.Users": [
    "widget.users"
  ],
  "Ext.ux.event.Maker": [],
  "Packt.controller.Main": [],
  "Packt.model.customer.Address": [],
  "Packt.view.security.GroupsEdit": [
    "widget.groupsedit"
  ],
  "Packt.view.reports.SalesFilmCategoryPie": [
    "widget.salesfilmcategorypie"
  ],
  "Ext.ux.DataView.Draggable": [],
  "Packt.controller.TranslationManager": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Packt.view.mail.MailMenu": [
    "widget.mailMenu"
  ],
  "Packt.view.staticData.AbstractGrid": [
    "widget.staticdatagrid"
  ],
  "Packt.proxy.StaticData": [
    "proxy.staticdataproxy"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Packt.model.staticData.Actor": [],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Packt.view.film.Films": [
    "widget.filmsgrid"
  ],
  "Packt.proxy.Sakila": [
    "proxy.sakila"
  ],
  "Packt.store.customer.Addresses": [],
  "Packt.view.mail.MailContainer": [
    "widget.mailcontainer"
  ]
});
