INSERT INTO `menu` (`id`,`text`,`iconCls`,`className`,`menu_id`) VALUES (1,'menu1','fa fa-group fa-lg',NULL,NULL);
INSERT INTO `menu` (`id`,`text`,`iconCls`,`className`,`menu_id`) VALUES (2,'menu11','xf0c0','groups',1);
INSERT INTO `menu` (`id`,`text`,`iconCls`,`className`,`menu_id`) VALUES (3,'menu12','xf007','user',1);
INSERT INTO `menu` (`id`,`text`,`iconCls`,`className`,`menu_id`) VALUES (4,'staticData','fa fa-database fa-lg',NULL,NULL);
INSERT INTO `menu` (`id`,`text`,`iconCls`,`className`,`menu_id`) VALUES (5,'actors','xf005','actorsgrid',4);
INSERT INTO `menu` (`id`,`text`,`iconCls`,`className`,`menu_id`) VALUES (6,'categories','xf013','categoriesgrid',4);
INSERT INTO `menu` (`id`,`text`,`iconCls`,`className`,`menu_id`) VALUES (7,'languages','xf1ab','languagesgrid',4);
INSERT INTO `menu` (`id`,`text`,`iconCls`,`className`,`menu_id`) VALUES (8,'cities','xf018','citiesgrid',4);
INSERT INTO `menu` (`id`,`text`,`iconCls`,`className`,`menu_id`) VALUES (9,'countries','xf0ac','countriesgrid',4);
INSERT INTO `menu` (`id`,`text`,`iconCls`,`className`,`menu_id`) VALUES (10,'cms','fa fa-film fa-lg',NULL,NULL);
INSERT INTO `menu` (`id`,`text`,`iconCls`,`className`,`menu_id`) VALUES (11,'films','xf1c8','films',10);
INSERT INTO `menu` (`id`,`text`,`iconCls`,`className`,`menu_id`) VALUES (12,'reports','fa fa-line-chart fa-lg',NULL,NULL);
INSERT INTO `menu` (`id`,`text`,`iconCls`,`className`,`menu_id`) VALUES (13,'salesfilmcategory','xf200','salesfilmcategory',12);
